dist: xenial
env:
  global:
  - TFBIN_DIR=$HOME/tfbin
  - TERRAFORM_VERSION=0.12.4
install:
- "./scripts/download_terraform.sh $TERRAFORM_VERSION"
script:
- "~/tfbin/terraform fmt -write=false -diff=true -check"
notifications:
  email: false
  slack:
    rooms:
      secure: C3H4FE+vqUpJV+gu+0aTj4dE9nIKO6vCd5FuD7EMhREzCAR1Xwy3T5w3Z6xLPCtU2PXF9OB+2TZWb2VXMawUCwgUdH8NwMXjycezt4e/Wd3KUzdthbZZkRcDDFemEk8LPcILNOouP7t4s3viNQX8nb3gkiwBDWKQIo8jK2XXsqzYMHJjHEUCFSPQyhbPwHvV/BIcY3bGJ8nCV4aUQjyWM38dlssh5evTvNHpNw2RImAm8QXOEgZrg72Sxnh3KYA/hlfUa/myWBS2W/L6osy5hF91hRkckRGwHt9x4k6srSHX1TCV/ETly7im5TqL6ksdFnbMNqiK+YzaKXqPq8JxVwwQ6LIF9qJBbhccvOzb74exxmqGYZsvtdOgj+rh5oMG3jyAukMSxqlh2G39TkpHIhOocRV+7fybY3H8eqqFiRgSdQ2R6gdGHX72GXPnFE7SUv/BKoNemI4lzhCA6RY3JZ10yN8Kn/VZ6T/CknuRuUz5hwjl35PTbmC4X5iNcpd08ye8XldnBQHsEVWdCLNz8ArCpl3D/U+LK23rieUq4hnYkInY9wZh7mC389GUfq64MrCn6B6ylOeUz5McX2284jKViFlUo5CCrSRKnVIH6YUotI0GmQy4KDn7QjYreW4KC0WBrDyn/pluOaHkHb6p2IrZsMVguYskpeDB4p58CI4=
